### PR TITLE
pass missing initializeDatabase property to WasmProbeResult.open

### PR DESCRIPTION
**Pull request by nmfisher**
`WasmDatabase.open` takes an `initializeDatabase` argument, but this is never passed to `WasmProbeResult.open` so it's never actually called.

### CODE REVIEW

**Review by simolus3 — APPROVED** [review]
Ouch! Thanks for the fix.

Could you add tests for this as well? These are failing currently and should get fixed by your PR:

```patch
diff --git a/extras/integration_tests/web_wasm/test/drift_wasm_test.dart b/extras/integration_tests/web_wasm/test/drift_wasm_test.dart
index 0e845463..2b99d4f7 100644
--- a/extras/integration_tests/web_wasm/test/drift_wasm_test.dart
+++ b/extras/integration_tests/web_wasm/test/drift_wasm_test.dart
@@ -85,10 +85,27 @@ void main() {
         expect(result.storages, expectedImplementations);
       });
 
+      test('via regular open', () async {
+        await driver.openDatabase();
+        expect(await driver.amountOfRows, 0);
+
+        await driver.insertIntoDatabase();
+        await driver.waitForTableUpdate();
+        expect(await driver.amountOfRows, 1);
+      });
+
+      test('regular open with initializaton', () async {
+        await driver.enableInitialization(InitializationMode.loadAsset);
+        await driver.openDatabase();
+
+        expect(await driver.amountOfRows, 1);
+      });
+
       for (final entry in browser.availableImplementations) {
         group(entry.name, () {
           test('basic', () async {
             await driver.openDatabase(entry);
+            expect(await driver.amountOfRows, 0);
 
             await driver.insertIntoDatabase();
             await driver.waitForTableUpdate();
```

**Comment by nmfisher** [comment]
I've added those tests (which pass) but a lot of the existing tests are failing:

<details>

<summary>Failing log output</summary>

```
00:19 +6 -1: test/drift_wasm_test.dart: chrome opfsLocks initialization from custom wasmdatabase [E]                                                                                                             
  Expected: <1>
    Actual: <0>
  
  package:matcher                   expect
  test/drift_wasm_test.dart 189:17  main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome opfsLocks initialization from custom wasmdatabase'
00:20 +6 -2: test/drift_wasm_test.dart: chrome sharedIndexedDb basic [E]                                                                                                                                         
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 109:20     main.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome sharedIndexedDb basic'
00:23 +7 -3: test/drift_wasm_test.dart: chrome sharedIndexedDb initialization from static blob [E]                                                                                                               
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 169:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome sharedIndexedDb initialization from static blob'
00:25 +7 -4: test/drift_wasm_test.dart: chrome sharedIndexedDb initialization from custom wasmdatabase [E]                                                                                                       
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 189:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome sharedIndexedDb initialization from custom wasmdatabase'
00:26 +7 -5: test/drift_wasm_test.dart: chrome unsafeIndexedDb basic [E]                                                                                                                                         
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 109:20     main.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome unsafeIndexedDb basic'
00:29 +8 -6: test/drift_wasm_test.dart: chrome unsafeIndexedDb initialization from static blob [E]                                                                                                               
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 169:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome unsafeIndexedDb initialization from static blob'
00:31 +8 -7: test/drift_wasm_test.dart: chrome unsafeIndexedDb initialization from custom wasmdatabase [E]                                                                                                       
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 189:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome unsafeIndexedDb initialization from custom wasmdatabase'
00:35 +10 -8: test/drift_wasm_test.dart: chrome inMemory initialization from custom wasmdatabase [E]                                                                                                             
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 189:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome inMemory initialization from custom wasmdatabase'
00:38 +10 -9: test/drift_wasm_test.dart: chrome keep existing IndexedDB database after OPFS becomes available [E]                                                                                                
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 217:20     main.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome keep existing IndexedDB database after OPFS becomes available'
00:42 +10 -10: test/drift_wasm_test.dart: chrome uses indexeddb after OPFS becomes unavailable [E]                                                                                                               
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 233:20     main.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'chrome uses indexeddb after OPFS becomes unavailable'
01:07 +16 -11: test/drift_wasm_test.dart: firefox opfsShared initialization from custom wasmdatabase [E]                                                                                                         
  Expected: <1>
    Actual: <0>
  
  package:matcher                   expect
  test/drift_wasm_test.dart 189:17  main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'firefox opfsShared initialization from custom wasmdatabase'
01:17 +18 -11: test/drift_wasm_test.dart: firefox opfsLocks initialization from static blob                                                                                                                      
  Skip: This configuration fails, but the failure can't be reproduced by manually running the steps of this test.
01:17 +18 ~1 -11: test/drift_wasm_test.dart: firefox opfsLocks initialization from custom wasmdatabase                                                                                                           
  Skip: This configuration fails, but the failure can't be reproduced by manually running the steps of this test.
01:19 +18 ~2 -12: test/drift_wasm_test.dart: firefox sharedIndexedDb basic [E]                                                                                                                                   
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 109:20     main.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'firefox sharedIndexedDb basic'
01:27 +19 ~2 -13: test/drift_wasm_test.dart: firefox sharedIndexedDb initialization from static blob [E]                                                                                                         
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 169:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'firefox sharedIndexedDb initialization from static blob'
01:31 +19 ~2 -14: test/drift_wasm_test.dart: firefox sharedIndexedDb initialization from custom wasmdatabase [E]                                                                                                 
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 189:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'firefox sharedIndexedDb initialization from custom wasmdatabase'
01:35 +19 ~2 -15: test/drift_wasm_test.dart: firefox unsafeIndexedDb basic [E]                                                                                                                                   
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 109:20     main.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'firefox unsafeIndexedDb basic'
01:43 +20 ~2 -16: test/drift_wasm_test.dart: firefox unsafeIndexedDb initialization from static blob [E]                                                                                                         
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 169:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'firefox unsafeIndexedDb initialization from static blob'
01:47 +20 ~2 -17: test/drift_wasm_test.dart: firefox unsafeIndexedDb initialization from custom wasmdatabase [E]                                                                                                 
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 189:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'firefox unsafeIndexedDb initialization from custom wasmdatabase'
01:58 +22 ~2 -18: test/drift_wasm_test.dart: firefox inMemory initialization from custom wasmdatabase [E]                                                                                                        
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 189:24     main.<fn>.<fn>.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'firefox inMemory initialization from custom wasmdatabase'
02:05 +22 ~2 -19: test/drift_wasm_test.dart: firefox keep existing IndexedDB database after OPFS becomes available [E]                                                                                           
  type 'Null' is not a subtype of type 'FutureOr<int>'
  package:web_wasm/driver.dart 143:12  DriftWebDriver.amountOfRows
  ===== asynchronous gap ===========================
  test/drift_wasm_test.dart 217:20     main.<fn>.<fn>
  

To run this test again: /Users/nickfisher/Downloads/flutter/bin/cache/dart-sdk/bin/dart test test/drift_wasm_test.dart -p vm --plain-name 'firefox keep existing IndexedDB database after OPFS becomes available'
02:05 +22 ~2 -19: Some tests failed.                                                                                                                                                                             
```

</details>

These fail on `develop`, too, so I don't think this PR has specifically broken anything.

Any suggestions as to the best place to start looking to fix these?

I wonder if this is related to the actual underlying issue I'm trying to fix - pre-populating a database with a `Uint8List` returned from `initializeDatabase`. This was working when I used the JS implementation:

```
final storage = drift_web.DriftWebStorage.indexedDb("anki");
await storage.open();
storage.store(collectionData!);
await storage.close();
var db = drift_web.WebDatabase.withStorage(storage);     
```

but when I switched to the wasm shared worker implementation, it's failing:

```
final dbResult = await WasmDatabase.open(
        databaseName: "anki",
        sqlite3Uri: Uri.parse("sqlite3.wasm"),
        driftWorkerUri: Uri.parse("drift_worker.js"),
        initializeDatabase: () {
          return collectionData;
        });
var db = dbResult.resolvedExecutor;
```

With this PR, I can see that `initializeDatabase` is actually called and the data is properly written to/read back from the virtual filesystem, but then the following will always be thrown:

`Error: SqliteException(26): while selecting from statement, file is not a database, file is not a database (code 26)
  Causing statement: PRAGMA user_version;`

Given I can open an empty WasmDatabase (i.e. without passing `initializeDatabase`), there seems to be some issue with initializing the database with an existing file on the VFS.  That seems like it could be related to the failing tests?

**Comment by nmfisher** [comment]
Actually I managed to resolve the test issue (I think, anyway?), I suspect there was an old file in the VFS IndexedDB cache from when I was manually experimenting with files.

Still trying to figure out the issue with my app though.

**Comment by simolus3** [comment]
Could there be a similar cause in your app?

The tests are passing for me as well, so I'll merge this and release a patch to pub.dev soon.

**Comment by nmfisher** [comment]
I managed to track down the source of the problem in my app - it's unrelated to this PR, so will open a separate issue.

I was waiting until I was certain they were unrelated before pushing the tests but looks like you beat me to it!

**Pull request merged**
