### PR TITLE
refactor: integrate with melos

### PR DESCRIPTION
**Pull request by Ehesp**

### CODE REVIEW

**Comment by Ehesp** [comment]
cc @salakar

**Comment by simolus3** [comment]
There are also packages in `extras/integration_tests/vm`, `extras/integration_tests/web`, ..., can those be managed with melos as well?

I like putting the packages into a child folder, but I want `docs/` to stay a top-level directory, is that possible?

**Comment by Ehesp** [comment]
Ok cool have updated that. Docs moved to root and tests are managed via melos too

```
Running "flutter pub get" in workspace packages...
Note: this may take a while in large workspaces such as this one.
  ✓ analyzer_load_drift_plugin
    └> packages/drift/tools/analyzer_plugin
  ✓ analyzer_load_moor_plugin
    └> packages/moor/tools/analyzer_plugin
  ✓ benchmarks
    └> extras/benchmarks
  ✓ drift
    └> packages/drift
  ✓ drift_dev
    └> packages/drift_dev
  ✓ drift_postgres
    └> extras/drift_postgres
  ✓ encrypted_moor
    └> extras/encryption
  ✓ flutter_db
    └> extras/integration_tests/ffi_on_flutter
  ✓ flutter_web_worker_example
    └> extras/flutter_web_worker_example
  ✓ migrations_example
    └> extras/migrations_example
  ✓ moor
    └> packages/moor
  ✓ moor_documentation
    └> docs
  ✓ moor_example
    └> packages/moor_flutter/example
  ✓ moor_flutter
    └> packages/moor_flutter
  ✓ moor_flutter_integration_test
    └> extras/integration_tests/moor_flutter
  ✓ moor_generator
    └> packages/moor_generator
  ✓ pg
    └> extras/integration_tests/postgres
  ✓ plugin_example
    └> extras/plugin_example
  ✓ sqlparser
    └> packages/sqlparser
  ✓ tests
    └> extras/integration_tests/tests
  ✓ tooling
    └> extras/tooling
  ✓ vm
    └> extras/integration_tests/vm
  ✓ web
    └> extras/integration_tests/web
  ✓ web_worker_example
    └> extras/web_worker_example
  ✓ with_built_value
    └> extras/with_built_value

Linking workspace packages...
  > SUCCESS

Generating IntelliJ IDE files...
  > SUCCESS

 -> 25 plugins bootstrapped
```

**Comment by Salakar** [comment]
It might be worth in this PR leaving the packages in the current locations and doing a move separately in another PR - to minimise conflicts, since having a `package` folder is not required but only a recommendation

**Comment by Ehesp** [comment]
Closing in favour of https://github.com/simolus3/drift/pull/1734

**Pull request closed without merging**
