### PR TITLE
Rewrite TypeConverter to null aware by default

### PR DESCRIPTION
**Pull request by westito**
DSL table declaration is type safe by default. You can't use nullable (sql) type converter on a not null column, but you can use non-nullable (sql) type converter on null column. With `UseRowClass` the generator will display warning when you use nullable converter on non-nullable field. Generated data class is always match the type converter (dart) type.

For Drift files there is a warning when you want to use nullable TypeConverter on not null column. Vice versa is working. You can use a nullable TypeConverter on a not null column.

```
line 24, column 33: The column declared as not null, but TypeConverter SQL type argument is nullable
   ╷
24 │     sync_state INTEGER not null MAPPED BY `const NullableSyncTypeConverter()`,
   │                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

### CODE REVIEW

**Comment by westito** [comment]
#1561

**Comment by simolus3** [comment]
Thanks for working on this! I should note that this is a breaking change, so we'd have to do a Drift 2.0 for this. I'll try to get the current features on `develop` and DSL views into a new version first, then we can bundle up all breaking change ideas afterwards.

**Comment by westito** [comment]
The current develop branch will be released as 2.0?

**Comment by simolus3** [comment]
I would prefer to release `develop` (after merging your views feature) as drift 1.1.

If there are enough breaking changes bundled up, I'll start merging this and apply the other breaking changes too. Then we can release that as drift 2.0

**Comment by North101** [comment]
Does it make sense to combine JsonTypeConverter into TypeConverter?

**Comment by simolus3** [comment]
Thanks for the contribution! I've applied a similar change inspired by your work in 06af930941407e16b3a0f2f1bdeb5b7d9038fcb2.

**Comment by westito** [comment]
I tried to do a TypeConverter that can handle nullable and non-nullable fields with a single converter.

```dart
class Table {
  IntColumn get defaultLanguage =>
      integer().nullable().map(const EnumConv<Language?>(Language.values))();

  IntColumn get defaultLanguage2 =>
      integer().map(const EnumConv<Language>(Language.values))();
}
```

Version 1:
```dart
class EnumConv<T extends BaseEnum?> extends TypeConverter<T, int?> {
  final List<T> _values;

  const EnumConv(this._values);

  @override
  T fromSql(int? fromDb) {
    return (fromDb == null ? null : _values[fromDb]) as T;
  }

  @override
  int? toSql(T? value) {
    return value?.index;
  }
}
```

Version 2:
```dart
class EnumConv2<T extends BaseEnum?> extends NullAwareTypeConverter<T, int> {
  final List<T> _values;

  const EnumConv2(this._values);

  @override
  T requireFromSql(int? fromDb) {
    return _values[fromDb!];
  }

  @override
  int requireToSql(T value) {
    return value!.index;
  }
}
```

Version 1 works as expected, and there is no syntax errors.
```dart
class GeneratedModel {
  final Language? defaultLanguage;
  final Language defaultLanguage2;
}
```

But I want to simplify and eliminate that null check I thing NullAware should does this. But when I regenerate the code with version 2, the generated class has wrong null type:
```dart
class GeneratedModel {
  final Language? defaultLanguage;
  final Language? defaultLanguage2;
}
```

The problem is NullAware converter always converts `D` type to `D?`
```dart
abstract class NullAwareTypeConverter<D, S extends Object>
    extends TypeConverter<D?, S?>
```
 That's why the generator generates data class property as nullable even it should be non-null. 

The solution is remove `?` mark from `D?` in extends and add a type cast to `D` like in my converter above. The type cast will always be succeed because `requireFromSql` return type matches nullability of `D`

**Pull request closed without merging**
