### PR TITLE
fix: Fix error message for non nullable converter

### LINKED ISSUE #2854: Wrong message when a non nullable converter is used on a nullable column:
```console
This column is nullable, but the type converter has a non-nullable SQL type, meaning that it won't be able to map `null` from the database to Dart.
Try wrapping the converter in `JsonTypeConverter.asNullable`
   ╷
49 │   IntColumn get myColumn => integer().map(const MyConverter()).nullable()();
   │         
```

But `JsonTypeConverter.asNullable` doesn't exist, it should be replaced with `JsonTypeConverter2.asNullable`

### PR DESCRIPTION
**Pull request by ValentinVignal**
Fixes https://github.com/simolus3/drift/issues/2854

### CODE REVIEW

**Review by simolus3 — APPROVED** [review]
Thanks!

**Comment by ValentinVignal** [comment]
I quickly looked around and wasn't able to find if you have already written some tests for reported errors.

Where / how do you want me to write a test for that?

**Comment by simolus3** [comment]
I think this assertion just needs to be expanded to cover the full message:

https://github.com/simolus3/drift/blob/261c151fbf87a580b07bc8565afbd9d7f16e9a07/drift_dev/test/analysis/resolver/dart/type_converter_test.dart#L85-L86

**Comment by ValentinVignal** [comment]
Thank you @simolus3 , I implemented a test in [test: Update the tests](https://github.com/simolus3/drift/pull/2855/commits/b03805d3995ae56581dbcf5015c5013fe1928d01)

**Pull request merged**
