### PR TITLE
`managers` extends public classes

### LINKED ISSUE #3015: Database can no longer be mocked with new manager API
**Describe the bug**
After upgrading drift (currently on 2.18), the `build_runner` outputs the following error when it tries to generate a mocked version of my database:
```
Invalid @GenerateMocks annotation: Mockito cannot generate a valid mock class which implements 'MyDatabase' for the following reasons:
    The property accessor '_$MyDatabase.managers' features a private return type, and cannot be stubbed. Try generating this mock with a MockSpec with 'unsupportedMembers' or a dummy generator (see https://pub.dev/documentation/mockito/latest/annotations/MockSpec-class.html).
```
I tried to follow the advice in the message and add a `MockSpec`, but to no avail for now. Is it necessary/expected that I need to add the custom mock spec, or is this an unintended result of recent changes in drift/drift_dev?

My annotation (I added the `customMocks` after first getting this error):
```dart
@generateMocks(
  [MyDatabase],
  customMocks: [
    MockSpec<MyDatabase>(unsupportedMembers: {#_$MyDatabase.managers}),
  ]
)
```

### PR DESCRIPTION
**Pull request by dickermoshe**
Instead of managers being fields on private classes:
```dart
class _Database extends GeneratedDatabase {
  Managers get managers => Managers(this);
}
Managers {
  // Private: Bad for Mockito
  final _Database db;
}

```
We now have them on extension on the public class:
```dart
class _Database extends GeneratedDatabase {
  ...
}
Managers {
  // Public
  final Database db;
}

extension DatabaseManagersExt on Database {
  Managers get managers => Managers(this);
}
```

This will allow mockito to do whatever it wants as Manager doesn't rely on a private class
closes https://github.com/simolus3/drift/issues/3015

### CODE REVIEW

**Comment by simolus3** [comment]
Why do they have to be extensions? So that mockito doesn't try to mock them?

**Comment by dickermoshe** [comment]
What does the Managers class use?
```dart
Managers {
  // Private: Bad for Mockito
  final _Database db;
}
```
A private `_Database` class, so `db.managers` can't be mocked.

Hmm, lets make it work with the public one:
```dart
Managers {
  // Public!
  final Database db;
}
```
Ok, but wait:
```dart
class _Database extends GeneratedDatabase {
  Managers get managers => Managers(this); // BAD! `this` is not a `Database` its a `_Database `
}
```
So the only way `this` is a `Database` is if we use an `extension`.
```dart
extension DatabaseManagersExt on Database {
  Managers get managers => Managers(this);
}
```

What do you think?

**Comment by dickermoshe** [comment]
There is a bug in mockito which is not allowing us to mock individual managers, I'm going to make a repro and open an issue on their repo, it's a mockito issue, not a drift one

**Comment by simolus3** [comment]
Is there a way to test that we're not breaking mockito as part of the CI? We're already running that builder on `drift` so I think it should be possible? It would be good if we could detect regressions automatically once this is fixed.

**Comment by dickermoshe** [comment]
@simolus3 Did you ever have this?
The analyzer returning the underlying type instead of the typedef itself?

https://github.com/dart-lang/mockito/issues/775#issuecomment-2442901089

This is blocking the mocking of actual managers.

**Comment by dickermoshe** [comment]
I've added the database manager (db.managers) to the mockito so we know that now works, before it didn't.
However table managers still cant be mocked (db.managers.todos) due to a mockito bug.

This PR includes a mock that tests itself

https://github.com/simolus3/drift/pull/3314/files#diff-1cc77f2eccd6a270ee306cd04f5e9fd10d81e1431736ba0bbf8cfc7555a0d990R6-R9

**Comment by dickermoshe** [comment]
Opened a [PR](https://github.com/dart-lang/mockito/pull/776) on mockito, if you know someone at google that can expedite this review I would appreciate it.


 But this PR is good to go. Let mockito figure themselves out.

**Comment by dickermoshe** [comment]
My PR for mockito is complete. Hopefully they cherry-pick it into a release.

**Comment by dickermoshe** [comment]
Argh!
You can't mock extensions!
https://github.com/dart-lang/build/issues/4768

**Comment by dickermoshe** [comment]
Modular generation fixes this entire mess! Maybe we should add this to the docs. It makes a public base class

**Pull request closed without merging**
